language: python
python:
  - "2.7"
  - "3.4"
  - "3.5.1"  # Special, it doesn't have typing.Text
  - "3.5"  # Latest, e.g. 3.5.4
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  include:
    - python: '3.6'
      env: USE_MYPY=true
    - python: '3.7'
      env: USE_MYPY=true
    - python: '3.8-dev'
      env: USE_MYPY=true
  
install:
  - pip install -r requirements.txt
  - if [[ $USE_MYPY == true ]]; then pip install -U mypy; fi
script:
  - pytest
  - if [[ $USE_MYPY == true ]]; then mypy pyannotate_*; fi
